###############################################################################
# Docker Compose - VOTS Full Multi-Service (Extended with LocalAI placeholder)
###############################################################################

services:

  ######################################################################
  # 1) Python Agent (synergy + PDF ingestion)
  ######################################################################
  python_agent:
    build:
      context: ./python_agent
      dockerfile: Dockerfile
    container_name: python_agent
    env_file: .env
    networks:
      - vots_network
    ports:
      - "${FASTAPI_PORT:-9000}:9000"
      - "${GRADIO_PORT:-8500}:8500"
    restart: unless-stopped
    depends_on:
      - c_service
      - go_service
      - rust_service
      - vots_mongo
      # (Optional) If synergy logic requires localai, uncomment next line:
      # - localai

  ######################################################################
  # 2) C Microservice
  ######################################################################
  c_service:
    build:
      context: ./c_service
      dockerfile: Dockerfile
    container_name: c_service
    env_file: .env
    networks:
      - vots_network
    ports:
      - "${C_PORT:-5000}:5000"
    restart: unless-stopped

  ######################################################################
  # 3) Go Microservice
  ######################################################################
  go_service:
    build:
      context: ./go_service
      dockerfile: Dockerfile
    container_name: go_service
    env_file: .env
    networks:
      - vots_network
    ports:
      - "${GO_PORT:-4000}:4000"
    restart: unless-stopped

  ######################################################################
  # 4) Rust Microservice
  ######################################################################
  rust_service:
    build:
      context: ./rust_service
      dockerfile: Dockerfile
    container_name: rust_service
    env_file: .env
    networks:
      - vots_network
    ports:
      - "${RUST_PORT:-3500}:3000"
    restart: unless-stopped
    # depends_on removed to avoid cyclical dependency

  ######################################################################
  # 5) Next.js Dashboard (port 3001)
  ######################################################################
  nextjs_dashboard:
    build:
      context: ./nextjs_dashboard
      dockerfile: Dockerfile
    container_name: nextjs_dashboard
    env_file: .env
    networks:
      - vots_network
    ports:
      - "${NEXTJS_PORT:-3001}:3000"
    restart: unless-stopped
    depends_on:
      - python_agent
      - rust_service
      # (Optional) If synergy logic requires localai, uncomment next line:
      # - localai

  ######################################################################
  # 6) Mongo container
  ######################################################################
  vots_mongo:
    image: mongo:6
    container_name: vots_mongo
    networks:
      - vots_network
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mysecret
    ports:
      - "27017:27017"

  ######################################################################
  # 7) LocalAI container (Optional, CPU-based)
  #    If synergy logic doesn't require LocalAI, remove this block.
  ######################################################################
  localai:
    image: localai/localai:latest-aio-cpu
    container_name: localai
    env_file: .env
    networks:
      - vots_network
    ports:
      - "8080:8080"
    restart: unless-stopped

###############################################################################
# Shared network & volumes
###############################################################################
networks:
  vots_network:
    driver: bridge

volumes:
  chroma_data:
    driver: local
